### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by Zunwolf1896** [bunten2005/enderscape#12]
Have a server crash caused twice now by this mod, crash report here;
[crash-2022-06-29_17.19.47-server.txt](https://github.com/bunten2005/enderscape/files/9012757/crash-2022-06-29_17.19.47-server.txt)

**Comment by bunten2005** [comment]
Your crash report shows that you're using version 0.3.2. Please update to 0.3.3 and let me know afterwards if the crash still occurs.

**Comment by lunarbunten** [comment]
This has been fixed in v0.3.4. Please update to it.

https://modrinth.com/mod/enderscape/version/v0.3.4
