### ISSUE TITLE
better end compat

### ISSUE THREAD

**Issue by Chuunkyz** [bunten2005/enderscape#7]
hey, plz do that if you want more downloads lol

**Comment by paulevsGitch** [comment]
After [this commit](https://github.com/paulevsGitch/BetterEnd/commit/d8bad90731a5695fbb5e710952ab3fc77b687652) this will be not necessary (will appear in BE 0.12.4)

![image](https://user-images.githubusercontent.com/17707380/142864938-095cb44c-a081-4742-99ca-50668c5b2122.png)

**Comment by bunten2005** [comment]
Thank you very much for adding Enderscape support!
